// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfm5xXkWFwdgThrApoBadz4gW4Jsn8HoM',
    appId: '1:521495492124:web:fe7309578eb0ee27f1d1d9',
    messagingSenderId: '521495492124',
    projectId: 'chat-app-73ae6',
    authDomain: 'chat-app-73ae6.firebaseapp.com',
    storageBucket: 'chat-app-73ae6.appspot.com',
    measurementId: 'G-99GWQCMWBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeoRpo30iZj3ja1c3lkvC8rAnT7sRhaNE',
    appId: '1:521495492124:android:414573c4224c250ff1d1d9',
    messagingSenderId: '521495492124',
    projectId: 'chat-app-73ae6',
    storageBucket: 'chat-app-73ae6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtISSflj92u1lgz09JWJOFpdD6In8D9tk',
    appId: '1:521495492124:ios:36689d7d6c545860f1d1d9',
    messagingSenderId: '521495492124',
    projectId: 'chat-app-73ae6',
    storageBucket: 'chat-app-73ae6.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtISSflj92u1lgz09JWJOFpdD6In8D9tk',
    appId: '1:521495492124:ios:509da264af8e0022f1d1d9',
    messagingSenderId: '521495492124',
    projectId: 'chat-app-73ae6',
    storageBucket: 'chat-app-73ae6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfm5xXkWFwdgThrApoBadz4gW4Jsn8HoM',
    appId: '1:521495492124:web:1e7cd6ea1d9b5c01f1d1d9',
    messagingSenderId: '521495492124',
    projectId: 'chat-app-73ae6',
    authDomain: 'chat-app-73ae6.firebaseapp.com',
    storageBucket: 'chat-app-73ae6.appspot.com',
    measurementId: 'G-BNVBCZXLBF',
  );
}